Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EntidadTestClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using IdentityServer4;

namespace Dummy.Pages
{
    [AllowAnonymous]
    [BindProperties]
    public class IndexModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public IndexModel(SignInManager<IdentityUser> _signInManager)
        {
            this._signInManager = _signInManager;
            //this.Configuration = Configuration;
            Input = new InputModel();
            Dictionary<String, String> tipos = new Dictionary<string, string>();
            tipos = new Dictionary<string, string>();
            tipos.Add("CC", "Cédula de ciudadanía");
            tipos.Add("NI", "NIT");
            tipos.Add("CE", "Cédula de extranjería");
            Input.TiposIdentificacionOptions = new SelectList(tipos.ToList(), "Key", "Value");

            
        }
        //public IConfiguration Configuration { get; }
        public async void OnGet()
        {
            //   this.Input.acr_values = Configuration.GetSection("AuthConfiguration").Get<AuthConfiguration>().acr_values;
            this.Input.acr_values = "loa1";
            var result = await HttpContext.AuthenticateAsync();
            if (result?.Succeeded == true)
            {
                Input.idToken = result.Properties.GetTokenValue("id_token");
            }
            Input.Identificacion = "100";
            Input.TipoIdentificacion = "NI";

        }
        public IActionResult OnGetLogoutExternal()
        {
                        _signInManager.SignOutAsync();
            return SignOut("oidc");
        }

        public async void OnPostChallenge()
        {

        }

        [BindProperty]
        public InputModel Input { get; set; } = new InputModel();

        public class InputModel
        {
            public String acr_values { get; set; }
            public String loginHint { get; set; }
            public String ReturnUrl { get; set; }
            public String idToken { get; set; }
            public String TipoIdentificacion { get; set; }
            public String Identificacion { get; set; }
            public SelectList TiposIdentificacionOptions { get; set; }
        }
        public String Identificacion { get; set; }
        public String TipoIdentificacion { get; set; }


    }
}

Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EntidadClient.Pages
{
    [AllowAnonymous]

    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
            Input = new InputModel();

        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }


        [TempData]
        public string ErrorMessage { get; set; }
        [BindProperties]
        public class InputModel
        {

            public InputModel()
            {
                Dictionary<String, String> tipos = new Dictionary<string, string>();
                tipos = new Dictionary<string, string>();
                tipos.Add("CC", "Cédula de ciudadanía");
                //tipos.Add("NI", "NIT");
                tipos.Add("CE", "Cédula de extranjería");
                TiposIdentificacionOptions = new SelectList(tipos.ToList(), "Key", "Value");



            }
            /*   [Required]
               [EmailAddress]
               public string Email { get; set; }
               */
            public String acr_values { get; set; }
            public String loginHint { get; set; }
            public String ReturnUrl { get; set; }
            public String idToken { get; set; }
            [BindProperty]
            public String TipoIdentificacion { get; set; }
            [BindProperty]
            public String Identificacion { get; set; }

            [BindProperty]
            public String Idp { get; set; } = "";

            [BindProperty]
            public String TipoIdentificacionDependiente { get; set; }
            [BindProperty]
            public String IdentificacionDependiente { get; set; }

            [BindProperty]
            public String Nit { get; set; }
            public List<String> SelectedLoas { get; set; }

            public SelectList TiposIdentificacionOptions { get; set; }

            [BindProperty]
            public List<LOAClass> LoaOptions { get; set; }
            [BindProperties]
            public class LOAClass
            {
                [BindProperty]
                public String Key { get; set; }
                [BindProperty]
                public String Value { get; set; }

                [BindProperty]
                public int Index { get; set; }
                [BindProperty]
                public Boolean Selected { get; set; }
            }
        }


        public async Task OnGetAsync(string returnUrl = null)
        {
            if ( !string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostChallenge(string prov, string retUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            //tomar de la configuración.
            var selectedLoa = (from p in Input.LoaOptions
                               where p.Selected == true
                               select p.Key).ToList();


            var hint = Input.TipoIdentificacion + Input.Identificacion + "," + Input.Nit;
         
            retUrl = retUrl ?? Url.Content("~/");
            var props = new AuthenticationProperties
            {
                RedirectUri = Url.Action("Callback", "ExternalLogin"),
                Items =
                    {
                        { "returnUrl", retUrl },
                        { "scheme", prov },
                        { "acr_values", String.Join("", selectedLoa) + " " + Input.Idp },
                        { "login_hint", hint },

                    }
            };

            return new RedirectToPageResult("./ExternalLogin", "Challenge", new {    provider =prov,
                                                                                        acr_values = String.Join(" ", selectedLoa) + " " + Input.Idp,
                                                                                        hint ,
                                                                                        returnUrl = retUrl });

        }
        public IActionResult OnGetLogoutExternal()
        {
            _signInManager.SignOutAsync();
            return SignOut("oidc");
        }
        public async Task<IActionResult> OnPostChallengeRegister(string prov,  string retUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            //tomar de la configuración.
            var selectedLoa = (from p in Input.LoaOptions
                               where p.Selected = true
                               select p.Key).ToList();


            var hint = Input.TipoIdentificacion + Input.Identificacion + "," + Input.Nit;

            retUrl = retUrl ?? Url.Content("~/");/*
            var props = new AuthenticationProperties
            {
                RedirectUri = Url.Action("Callback", "ExternalLogin"),
                Items =
                    {
                        { "returnUrl", retUrl },
                        { "scheme", prov },
                        { "acr_values", "action:register" },
                        { "login_hint", hint },

                    }
            };*/

            // return Challenge(props, prov);


            return new RedirectToPageResult("./ExternalLogin", "Challenge", new
            {
                provider = prov,
                acr_values = String.Join("acr_values", "action:register"),
                login_hint= hint,
                returnUrl = retUrl
            });

        }
        public IActionResult OnPostPersonalizacion(string prov, string retUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }
            if (User.Identity.IsAuthenticated)
            {
                var claims = User.Claims;
                var subClaim= claims.Where(p => p.Type == "name").FirstOrDefault();
                if (subClaim != null)
                {
                    String hint = subClaim.Value;
                    retUrl = retUrl ?? Url.Content("~/");

                    return new RedirectToPageResult("./ExternalLogin", "Challenge", new
                    {
                        provider = prov,
                        acr_values = "action:manage",
                        login_hint = hint,
                        returnUrl = retUrl
                    });
                }
                
                //tomar de la configuración.
              
            }
            return Page();

         

        }

    }
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Entidad del Estado</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="https://cdn.www.gov.co/assets/css/styles.css" rel="stylesheet"/>
    <link href="/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <h3>Entidad del estado</h3>
            <nav class="navbar navbar-expand-lg fixed-top navbar-govco">
                <!--Nivel 1 - Sección de notificaciones -->
                <!--
        <div class="navbar-nav navbar-notifications">
            <div class="alert alert-warning">
                <div class="container p-0">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true"><i class="material-icons page-icon-close">clear</i></span>
                    </button>
                    <a href="/inicio#textarea-escribe-aqui-tu-opinion">
                        <strong class="page-alert-text">
                            Estamos construyendo este espacio para ti y tu opinión nos ayuda a crecer
                        </strong>
                    </a>
                </div>
            </div>
        </div>
            -->
                <!--Nivel 2 - Sección de navegación -->
                <div class="navbar-container">
                    <div class="navbar-logo float-left">
                        <a class="navbar-brand" href="http://190.60.233.154/">
                            <img src="https://cdn.www.gov.co/assets/images/logo.png" width="auto" height="30" alt="Logo Gov.co">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapsible" aria-controls="navbarCollapsible" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">

                        <ul class="navbar-nav mr-auto">
                        </ul>

                        @if (User.Identity.IsAuthenticated)
                        {

                            <div class="nav-item dropdown mr-0">


                                <a class="nav-item dropdown-toggle mr-3 mr-lg-0 text-white" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @User.Identity.Name
                                    <i class="fa fa-user"></i><span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

                                    <form id="personalizacionform" method="post" class="form-horizontal">

                                        <button type="submit" asp-page="Login" asp-page-handler="Personalizacion"
                                                class="dropdown-item btn btn-round btn-link "
                                                name="prov" value="oidc"
                                                title="Personalización">
                                            Personalización
                                        </button>
                                    </form>


                                    <a asp-page="Logout" asp-page-handler="LogoutExternal" class="dropdown-item btn btn-round btn-info ">
                                        Cerrar sesión
                                    </a>

                                </div>
                            </div>
                        }
                        else
                        {
                            <form id="loginform" method="post" class="form-horizontal">

                                @*<button type="submit" asp-page="Login" asp-page-handler="Challenge" class="btn btn-round btn-primary" name="prov" value="oidc"
                                        title="Iniciar sesión">
                                    Iniciar sesión
                                </button>*@

                            </form>

                        }
                    </div>

                    @*<div class="collapse navbar-collapse navbar-first-menu float-right">
            <div class="nav-primary">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Trámites y servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.gov.co/participacion">Participación</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.gov.co/informacion">Entidades</a>
                    </li>
                </ul>
            </div>
            <div class="nav-item-primary">
                <div class="form-inline form-search-bar my-2 my-lg-0">
                    <input class="form-control input-govco mr-sm-2 search-navbar"
                           type="search"
                           placeholder="Buscar"
                           aria-label="Search"
                           name="searchTerm"
                           id="searchTerm">
                    <span class="govco-icon govco-icon-search-n"></span>
                </div>
                <span class="govco-icon govco-icon-language-en-n lang-govco ml-3 mr-0"></span>
            </div>
        </div>*@
                </div>
                <!--Nivel 3 - Sección de menú flotante-->
                @*<div class="nav-secondary govco-content" id="nav-secondary">
                <div class="container">
                    <div class="collapse navbar-collapse navbar-first-menu">
                        <ul class="navbar-nav ml-auto mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Trámites y servicios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="https://www.gov.co/participacion">Participación</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="https://www.gov.co/informacion">Entidades</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>*@
            </nav>

         </nav>

    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Entidad del estado 
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>